apiVersion: apps/v1
kind: Deployment
metadata:
  name:  publisher-deployment
  namespace: default
  labels:
    app: ppublisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
        - env:
            - name: APPLICATION_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap-cf
                  key: publisherPort

            - name: APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: configmap-cf
                  key: publisherName

            - name: EVENT_PUBLISHER_URL
              valueFrom:
                configMapKeyRef:
                  name:  configmap-cf
                  key: publisherGraphql

          name:  publisher
          image:  'feezankhattak2208/publishersvc:1.0'
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 9093
              name: publisher-pod

---

apiVersion: v1
kind: Service
metadata:
  name:  publisher-svc
  namespace: default
  labels:
    app: publisher
spec:
  selector:
    app: publisher
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: publisher-pod
      nodePort: 30028