/*
 * Your Service Definition Using Internal JSON Schema
 * This is user Service API definition to enable its consumers to create, query, update details, and delete resource.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.greedycode.RegistrationService.dto;

import java.util.Objects;
import java.util.Arrays;
import co.greedycode.RegistrationService.dto.Error;
import co.greedycode.RegistrationService.dto.ServiceInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * ErrorResponseData
 */
@lombok.Builder @lombok.AllArgsConstructor @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ErrorResponseData implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_SERVICEINFO = "serviceinfo";
  @SerializedName(SERIALIZED_NAME_SERVICEINFO)
  private ServiceInfo serviceinfo;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private Error error;

  public ErrorResponseData() { 
  }

  public ErrorResponseData serviceinfo(ServiceInfo serviceinfo) {
    
    this.serviceinfo = serviceinfo;
    return this;
  }

   /**
   * Get serviceinfo
   * @return serviceinfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ServiceInfo getServiceinfo() {
    return serviceinfo;
  }


  public void setServiceinfo(ServiceInfo serviceinfo) {
    this.serviceinfo = serviceinfo;
  }


  public ErrorResponseData error(Error error) {
    
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Error getError() {
    return error;
  }


  public void setError(Error error) {
    this.error = error;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorResponseData errorResponseData = (ErrorResponseData) o;
    return Objects.equals(this.serviceinfo, errorResponseData.serviceinfo) &&
        Objects.equals(this.error, errorResponseData.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceinfo, error);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorResponseData {\n");
    sb.append("    serviceinfo: ").append(toIndentedString(serviceinfo)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

