/*
 * Your Service Definition Using Internal JSON Schema
 * This is user Service API definition to enable its consumers to create, query, update details, and delete resource.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.greedycode.EventPublisher.dto;

import java.util.Objects;
import java.util.Arrays;
import co.greedycode.EventPublisher.dto.LogEvent;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * Data
 */
@lombok.Builder @lombok.AllArgsConstructor @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Data implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_LOG_EVENT = "logEvent";
  @SerializedName(SERIALIZED_NAME_LOG_EVENT)
  private LogEvent logEvent;

  public Data() { 
  }

  public Data logEvent(LogEvent logEvent) {
    
    this.logEvent = logEvent;
    return this;
  }

   /**
   * Get logEvent
   * @return logEvent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LogEvent getLogEvent() {
    return logEvent;
  }


  public void setLogEvent(LogEvent logEvent) {
    this.logEvent = logEvent;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Data data = (Data) o;
    return Objects.equals(this.logEvent, data.logEvent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logEvent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Data {\n");
    sb.append("    logEvent: ").append(toIndentedString(logEvent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

